name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "ce44a190cd124558ab14610c1c32330d" # action部署时被变量替换

[triggers]
crons = ["0 16 * * *"] # action部署时被变量替换，默认为北京时间 9:00 和 21:00
